image:
  repository: mabecenter/erpnext
  tag: xxx
  pullPolicy: IfNotPresent

persistence:
  worker:
    storageClass: nfs

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: erp.cluster.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: erpnext-tls
      hosts:
        - erp.cluster.local
