apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: erpnext
  namespace: argocd
spec:
  destination:
    namespace: erpnext
    server: https://kubernetes.default.svc
  source:
    path: frappe/erpnext
    repoURL: https://github.com/mabecenter-it/argocd-app
    targetRevision: ${branch_name}
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
