{{- if .Values.jobs.restore.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  {{- if .Values.jobs.restore.jobName }}
  name: {{ .Values.jobs.restore.jobName }}
  {{- else }}
  name: {{ template "erpnext.fullname" . }}-restore-{{ now | date "20060102150405" }}
  {{- end }}
  labels:
    {{- include "erpnext.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.jobs.restore.backoffLimit }}
  template:
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "erpnext.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
      - name: restore
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["bash", "-c"]
        args:
          - |
            bench new-site localhost --no-mariadb-socket --db-type=mariadb --db-host=mariadb.database.svc.cluster.local --db-port=3306 --admin-password=changeit --mariadb-root-username=root --mariadb-root-password=SMNGg8X66YhT7UfW
            STORAGE_URL="http://store-hl.storage.svc.cluster.local:9000/erpnext/"
            AUTH="--user minio:minio123"
            RESTORE_DIR="/home/frappe/restore"
            SITE_NAME="{{ .Values.jobs.restore.siteName }}"  # Replace with actual site name if not using templating

            # Fetch the latest folder from the storage
            FOLDER=$(curl -s "${STORAGE_URL}?list-type=2" \
                | grep "<Key>" \
                | sed -n "s:.*<Key>\(.*\)</Key>.*:\1:p" \
                | awk -F'/' '{print $1}' \
                | sort | uniq | tail -n 1)

            if [ -z "$FOLDER" ]; then
              echo "No folder found."
              exit 1
            fi

            echo "Selected folder: $FOLDER"

            # Fetch the list of files in the selected folder
            FILES=$(curl -s "${STORAGE_URL}?list-type=2" \
                | grep -oP "(?<=<Key>${FOLDER}/).*?(?=</Key>)")

            if [ -z "$FILES" ]; then
              echo "No files found in folder $FOLDER."
              exit 1
            fi

            echo "Files to download:"
            echo "$FILES"

            # Create restore directory if it doesn't exist
            mkdir -p "$RESTORE_DIR"

            # Download each file
            for FILE in $FILES; do
              BASENAME=$(basename "$FILE")
              if [ -z "$BASENAME" ]; then
                echo "Invalid file name for $FILE."
                continue
              fi

              echo "Downloading $FILE as $BASENAME"
              # Use -f to fail on HTTP errors and -S for error messages
              curl -f -S "${STORAGE_URL}${FOLDER}/${FILE}" -o "${RESTORE_DIR}/${BASENAME}"

              echo "$STORAGE_URL $FOLDER / $FILE -> $RESTORE_DIR / $BASENAME"
              
              if [ $? -ne 0 ]; then
                echo "Error downloading $FILE"
                # Optionally, remove the incomplete file
                rm -f "${RESTORE_DIR}/${BASENAME}"
                continue
              fi
            done

            echo "Download process completed."

            DB_BACKUP_SQL=$(ls ${RESTORE_DIR}/*-database.sql.gz 2>/dev/null)

            #cp ${RESTORE_DIR}/*.json /home/frappe/frappe-bench/sites/${SITE_NAME}/site_config.json

            if [ -n "$DB_BACKUP_SQL" ]; then
              echo "Found uncompressed database backup: $DB_BACKUP_SQL"
              bench --site "$SITE_NAME" restore "$DB_BACKUP_SQL" --db-root-username=root --db-root-password=SMNGg8X66YhT7UfW
            else
              echo "No uncompressed database backup found."
            fi 
        env:
          - name: "SITE_NAME"
            value: "{{ .Values.jobs.restore.siteName }}"
        resources:
          {{- toYaml .Values.jobs.restore.resources | nindent 10 }}
        securityContext:
          {{- toYaml $.Values.securityContext | nindent 10 }}
        volumeMounts:
          - name: sites-dir
            mountPath: /home/frappe/frappe-bench/sites
          - name: logs
            mountPath: /home/frappe/frappe-bench/logs
          - name: restore-dir
            mountPath: /home/frappe/restore
      restartPolicy: Never
      volumes:
        - name: sites-dir
          {{- if .Values.persistence.worker.enabled }}
          persistentVolumeClaim:
            {{- if .Values.persistence.worker.existingClaim }}
            claimName: {{ .Values.persistence.worker.existingClaim }}
            {{- else }}
            claimName: {{ template "erpnext.fullname" . }}
            {{- end }}
            readOnly: false
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: logs
          {{- if .Values.persistence.logs.enabled }}
          persistentVolumeClaim:
            {{- if .Values.persistence.logs.existingClaim }}
            claimName: {{ .Values.persistence.logs.existingClaim }}
            {{- else }}
            claimName: {{ template "erpnext.fullname" . }}-logs
            {{- end }}
            readOnly: false
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: restore-dir
          emptyDir: {}
      {{- with .Values.jobs.restore.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jobs.restore.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jobs.restore.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
