{{- if .Values.jobs.restore.enabled }}

########################################################################
# 1) ConfigMap con el script Python                                    #
########################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "erpnext.fullname" . }}-restore-script
  labels:
    {{- include "erpnext.labels" . | nindent 4 }}
data:
  restore_db.py: |
    #!/usr/bin/env python3
    import os
    import sys
    import re
    import subprocess
    import glob

    def main():
        print("Starting restore_db.py")

        # 1) Leer variables de entorno
        storage_url = os.environ.get("STORAGE_URL", "")
        site_name = os.environ.get("SITE_NAME", "")
        restore_dir = "/home/frappe/restore"

        if not storage_url:
            print("Error: STORAGE_URL no está definido.")
            sys.exit(1)
        if not site_name:
            print("Error: SITE_NAME no está definido.")
            sys.exit(1)

        print(f"STORAGE_URL = {storage_url}")
        print(f"SITE_NAME = {site_name}")
        print(f"Restore dir = {restore_dir}")

        # 2) Listar objetos en el endpoint usando `curl -s "<storage_url>?list-type=2"`
        try:
            output = subprocess.check_output(
                ["curl", "-s", f"{storage_url}?list-type=2"],
                text=True
            )
        except subprocess.CalledProcessError as e:
            print(f"Error al listar objetos en {storage_url}:", e)
            sys.exit(1)

        # Filtra todas las claves entre <Key>...</Key>
        keys = re.findall(r"<Key>(.*?)</Key>", output)
        if not keys:
            print("No se encontraron archivos (Key) en el bucket.")
            sys.exit(1)

        # 3) Determinar la subcarpeta más reciente
        folders = set(k.split('/')[0] for k in keys if '/' in k)
        if not folders:
            print("No se encontraron subcarpetas en el listado.")
            sys.exit(1)

        folder_list_sorted = sorted(folders)
        folder = folder_list_sorted[-1]
        print(f"Subcarpeta seleccionada: {folder}")

        to_download = [k for k in keys if k.startswith(folder + "/")]
        if not to_download:
            print(f"No se encontraron archivos dentro de la subcarpeta '{folder}'.")
            sys.exit(1)

        # 4) Crear directorio de restore
        os.makedirs(restore_dir, exist_ok=True)

        # 5) Descargar cada archivo
        for file_key in to_download:
            basename = os.path.basename(file_key)
            if not basename:
                print(f"Archivo con nombre inválido: {file_key}. Se omite.")
                continue

            local_path = os.path.join(restore_dir, basename)
            download_url = f"{storage_url}{file_key}"  # asumiendo que STORAGE_URL termina con '/'

            print(f"Descargando {download_url} -> {local_path}")
            cmd = ["curl", "-f", "-S", download_url, "-o", local_path]
            ret = subprocess.run(cmd)
            if ret.returncode != 0:
                print(f"Error al descargar {file_key}")
                if os.path.exists(local_path):
                    os.remove(local_path)
                continue

        print("Descarga finalizada.")

        # 6) Localizar el archivo de DB
        db_files = glob.glob(os.path.join(restore_dir, "*-database.sql.gz"))
        if not db_files:
            print("No se encontró ningún archivo '-database.sql.gz' para restaurar.")
            sys.exit(0)

        db_backup_sql = db_files[0]
        print(f"Archivo de backup encontrado: {db_backup_sql}")

        # 7) Ejecutar bench restore
        root_user = "root"
        root_password = "SMNGg8X66YhT7UfW"

        restore_cmd = [
            "bench",
            "--site", site_name,
            "restore",
            db_backup_sql,
            f"--db-root-username={root_user}",
            f"--db-root-password={root_password}"
        ]

        print("Ejecutando restore con:", " ".join(restore_cmd))
        try:
            subprocess.run(restore_cmd, check=True)
            print("Restore completado con éxito.")
        except subprocess.CalledProcessError as e:
            print("Error durante la restauración:", e)
            sys.exit(1)

    if __name__ == "__main__":
        main()

---

########################################################################
# 2) Job que monta el script y lo ejecuta                              #
########################################################################
apiVersion: batch/v1
kind: Job
metadata:
  {{- if .Values.jobs.restore.jobName }}
  name: {{ .Values.jobs.restore.jobName }}
  {{- else }}
  name: {{ template "erpnext.fullname" . }}-restore-{{ now | date "20060102150405" }}
  {{- end }}
  labels:
    {{- include "erpnext.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.jobs.restore.backoffLimit }}
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "erpnext.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
      - name: restore
        # Imagen que contenga Python y bench
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["python3", "/scripts/restore_db.py"]
        env:
          - name: "SITE_NAME"
            value: "{{ .Values.jobs.restore.siteName }}"
          - name: "STORAGE_URL"
            value: "{{ .Values.jobs.restore.endpoint }}"
        resources:
          {{- toYaml .Values.jobs.restore.resources | nindent 10 }}
        securityContext:
          {{- toYaml $.Values.securityContext | nindent 10 }}
        volumeMounts:
          - name: restore-script
            mountPath: /scripts
            readOnly: true

          - name: sites-dir
            mountPath: /home/frappe/frappe-bench/sites
          - name: logs
            mountPath: /home/frappe/frappe-bench/logs
          - name: restore-dir
            mountPath: /home/frappe/restore

      restartPolicy: Never

      volumes:
        - name: restore-script
          configMap:
            name: {{ include "erpnext.fullname" . }}-restore-script
            items:
              - key: restore_db.py
                path: restore_db.py

        - name: sites-dir
          {{- if .Values.persistence.worker.enabled }}
          persistentVolumeClaim:
            {{- if .Values.persistence.worker.existingClaim }}
            claimName: {{ .Values.persistence.worker.existingClaim }}
            {{- else }}
            claimName: {{ template "erpnext.fullname" . }}
            {{- end }}
            readOnly: false
          {{- else }}
          emptyDir: {}
          {{- end }}

        - name: logs
          {{- if .Values.persistence.logs.enabled }}
          persistentVolumeClaim:
            {{- if .Values.persistence.logs.existingClaim }}
            claimName: {{ .Values.persistence.logs.existingClaim }}
            {{- else }}
            claimName: {{ template "erpnext.fullname" . }}-logs
            {{- end }}
            readOnly: false
          {{- else }}
          emptyDir: {}
          {{- end }}

        - name: restore-dir
          emptyDir: {}

      {{- with .Values.jobs.restore.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jobs.restore.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jobs.restore.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}